# Generated by Django 6.0.4 on 2026-04-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
